import { useState } from "react";
import { motion } from "framer-motion";
import { Map, Loader2, Lightbulb, Target, BookOpen } from "lucide-react";
import { generateRoadmap } from "../api/axios";
import toast from "react-hot-toast";

const WEAK_TOPICS = [
  "DSA",
  "OS",
  "DBMS",
  "Networking",
  "OOP",
  "Aptitude",
  "System Design",
  "HR",
  "SQL",
];

const COMPANIES = [
  "Product Based (FAANG)",
  "Service Based (TCS/Infosys)",
  "Startup",
  "Core Technical",
  "Mixed",
];

const Roadmap = () => {
  const [selectedTopics, setSelectedTopics] = useState([]);
  const [targetCompany, setTargetCompany] = useState("");
  const [timeframe, setTimeframe] = useState(4);
  const [roadmap, setRoadmap] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const toggleTopic = (topic) => {
    setSelectedTopics((prev) =>
      prev.includes(topic) ? prev.filter((t) => t !== topic) : [...prev, topic],
    );
  };

  const handleGenerate = async () => {
    if (selectedTopics.length === 0 || !targetCompany) {
      toast.error("Please select topics and target company");
      return;
    }
    try {
      setIsLoading(true);
      const res = await generateRoadmap({
        weakTopics: selectedTopics,
        targetCompany,
        timeframe,
      });
      setRoadmap(res.data.data);
      toast.success("Roadmap generated!");
    } catch (error) {
      toast.error("Failed to generate roadmap. Check OpenAI API key.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="page-container max-w-5xl mx-auto">
      <div className="flex items-center gap-3 mb-2">
        <div
          className="
        h-14 w-14
        rounded-2xl
        bg-gradient-to-br
        from-orange-500
        to-pink-600
        flex items-center justify-center
        shadow-lg
         "
        >
          <Map size={26} className="text-white" />
        </div>

        <div>
          <h1 className="text-4xl font-black text-gray-900 dark:text-white">
            AI Study Roadmap
          </h1>

          <p className="text-gray-500 dark:text-gray-400 mt-1">
            Personalized placement preparation roadmap generated by AI
          </p>
        </div>
      </div>

      {!roadmap ? (
        <>
          <div
            className="
    mt-8 mb-10
    rounded-[32px]
    overflow-hidden
    bg-gradient-to-r
    from-indigo-600
    via-purple-600
    to-pink-600
    p-8
    text-white
    shadow-[0_20px_60px_rgba(99,102,241,0.35)]
  "
          >
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6">
              <div>
                <span className="inline-flex items-center gap-2 bg-white/15 backdrop-blur-xl px-4 py-2 rounded-full text-sm font-medium">
                  🚀 AI Powered Learning Path
                </span>

                <h2 className="mt-5 text-4xl font-black">
                  Build Your Dream Placement Plan
                </h2>

                <p className="mt-3 text-white/80 max-w-2xl">
                  Select your weak areas, target company and preparation
                  timeline. PlacePrep AI will generate a personalized roadmap.
                </p>
              </div>

              <div className="grid grid-cols-3 gap-4">
                <div className="bg-white/10 backdrop-blur-xl rounded-3xl p-4 text-center">
                  <h3 className="text-3xl font-black">9+</h3>
                  <p className="text-white/70 text-sm">Topics</p>
                </div>

                <div className="bg-white/10 backdrop-blur-xl rounded-3xl p-4 text-center">
                  <h3 className="text-3xl font-black">12</h3>
                  <p className="text-white/70 text-sm">Weeks</p>
                </div>

                <div className="bg-white/10 backdrop-blur-xl rounded-3xl p-4 text-center">
                  <h3 className="text-3xl font-black">AI</h3>
                  <p className="text-white/70 text-sm">Generated</p>
                </div>
              </div>
            </div>
            </div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="
      relative
      overflow-hidden
      rounded-[36px]
      border border-gray-200/70
      dark:border-gray-700
      bg-white/80
      dark:bg-dark-200/80
      backdrop-blur-xl
      p-8 md:p-10
      shadow-[0_20px_60px_rgba(0,0,0,0.08)]
    "
            >
              <div className="absolute top-0 right-0 h-72 w-72 bg-indigo-500/10 blur-3xl rounded-full" />

              <div className="relative z-10">
                <div className="mb-8">
                  <span className="inline-flex items-center gap-2 rounded-full bg-indigo-100 dark:bg-indigo-900/20 px-4 py-2 text-indigo-600 text-sm font-semibold">
                    🚀 AI Powered Study Planner
                  </span>

                  <h2 className="mt-4 text-3xl font-black text-gray-900 dark:text-white">
                    Generate Your Personalized Roadmap
                  </h2>

                  <p className="mt-2 text-gray-500 dark:text-gray-400">
                    Select your weak topics, target company and preparation
                    duration.
                  </p>
                </div>

                {/* Weak Topics */}
                <div className="mb-8">
                  <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-4">
                    Select Weak Topics
                  </label>

                  <div className="flex flex-wrap gap-3">
                    {WEAK_TOPICS.map((topic) => (
                      <button
                        key={topic}
                        onClick={() => toggleTopic(topic)}
                        className={`px-4 py-2 rounded-2xl text-sm font-semibold transition-all ${
                          selectedTopics.includes(topic)
                            ? "bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-lg"
                            : "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 hover:bg-gray-200"
                        }`}
                      >
                        {topic}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Company */}
                <div className="mb-8">
                  <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">
                    Target Company Type
                  </label>

                  <select
                    value={targetCompany}
                    onChange={(e) => setTargetCompany(e.target.value)}
                    className="
            w-full
            rounded-2xl
            border border-gray-200
            dark:border-gray-700
            bg-white
            dark:bg-dark-300
            px-4 py-4
            outline-none
            focus:ring-4
            focus:ring-indigo-500/10
          "
                  >
                    <option value="">Select company type...</option>

                    {COMPANIES.map((c) => (
                      <option key={c} value={c}>
                        {c}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Slider */}
                <div className="mb-10">
                  <div className="flex items-center justify-between mb-3">
                    <label className="font-semibold text-gray-700 dark:text-gray-300">
                      Preparation Duration
                    </label>

                    <span className="bg-indigo-100 dark:bg-indigo-900/20 text-indigo-600 px-3 py-1 rounded-full text-sm font-semibold">
                      {timeframe} Weeks
                    </span>
                  </div>

                  <input
                    type="range"
                    min={1}
                    max={12}
                    value={timeframe}
                    onChange={(e) => setTimeframe(Number(e.target.value))}
                    className="w-full accent-indigo-600"
                  />
                </div>

                <button
                  onClick={handleGenerate}
                  disabled={
                    isLoading || selectedTopics.length === 0 || !targetCompany
                  }
                  className="
          w-full
          h-14
          rounded-2xl
          bg-gradient-to-r
          from-indigo-600
          via-purple-600
          to-pink-600
          text-white
          font-semibold
          shadow-xl
          hover:shadow-2xl
          transition-all
          flex items-center justify-center gap-2
        "
                >
                  {isLoading ? (
                    <>
                      <Loader2 size={18} className="animate-spin" />
                      Generating Roadmap...
                    </>
                  ) : (
                    <>
                      <Map size={18} />
                      Generate My Roadmap
                    </>
                  )}
                </button>
              </div>
            </motion.div>
          
        </>
      ) : (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-8"
        >
          {/* Premium Header */}
          <div
            className="
      relative overflow-hidden
      rounded-[36px]
      bg-gradient-to-r
      from-indigo-600
      via-purple-600
      to-pink-600
      p-8
      text-white
      shadow-[0_20px_60px_rgba(99,102,241,0.35)]
    "
          >
            <div className="absolute top-0 right-0 h-72 w-72 bg-white/10 rounded-full blur-3xl" />

            <div className="relative z-10">
              <div className="inline-flex items-center gap-2 bg-white/15 backdrop-blur-xl px-4 py-2 rounded-full text-sm font-medium">
                🗺️ AI Generated Roadmap
              </div>

              <h2 className="mt-5 text-3xl md:text-4xl font-black">
                {roadmap.title}
              </h2>

              <p className="mt-3 text-white/80">
                {timeframe}-week personalized preparation plan for{" "}
                {targetCompany}
              </p>
            </div>
          </div>

          {/* Weekly Timeline */}
          <div className="space-y-6">
            {roadmap.weeks?.map((week, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, x: -30 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: index * 0.08 }}
                className="
          relative
          overflow-hidden
          rounded-[32px]
          border border-gray-200
          dark:border-gray-700
          bg-white
          dark:bg-dark-200
          p-8
          shadow-xl
          hover:shadow-2xl
          transition-all
        "
              >
                {/* Week Number */}
                <div
                  className="
            absolute
            top-4
            right-6
            text-7xl
            font-black
            text-gray-100
            dark:text-white/5
            select-none
          "
                >
                  {week.week}
                </div>

                <div className="relative z-10">
                  <div className="flex items-center gap-4 mb-6">
                    <div
                      className="
                h-14 w-14
                rounded-2xl
                bg-gradient-to-r
                from-indigo-600
                to-purple-600
                text-white
                flex items-center justify-center
                font-black
                shadow-lg
              "
                    >
                      {week.week}
                    </div>

                    <div>
                      <p className="text-xs uppercase tracking-wider text-indigo-600 font-semibold">
                        Week {week.week}
                      </p>

                      <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                        {week.focus}
                      </h3>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    {/* Topics */}
                    <div className="rounded-2xl bg-indigo-50 dark:bg-indigo-900/20 p-5">
                      <p className="font-semibold text-indigo-600 flex items-center gap-2 mb-4">
                        <BookOpen size={16} />
                        Topics
                      </p>

                      <ul className="space-y-2">
                        {week.topics?.map((t, i) => (
                          <li
                            key={i}
                            className="text-sm text-gray-700 dark:text-gray-300"
                          >
                            • {t}
                          </li>
                        ))}
                      </ul>
                    </div>

                    {/* Resources */}
                    <div className="rounded-2xl bg-yellow-50 dark:bg-yellow-900/20 p-5">
                      <p className="font-semibold text-yellow-600 flex items-center gap-2 mb-4">
                        <Lightbulb size={16} />
                        Resources
                      </p>

                      <ul className="space-y-2">
                        {week.resources?.map((r, i) => (
                          <li
                            key={i}
                            className="text-sm text-gray-700 dark:text-gray-300"
                          >
                            • {r}
                          </li>
                        ))}
                      </ul>
                    </div>

                    {/* Goals */}
                    <div className="rounded-2xl bg-green-50 dark:bg-green-900/20 p-5">
                      <p className="font-semibold text-green-600 flex items-center gap-2 mb-4">
                        <Target size={16} />
                        Goals
                      </p>

                      <ul className="space-y-2">
                        {week.goals?.map((g, i) => (
                          <li
                            key={i}
                            className="text-sm text-gray-700 dark:text-gray-300"
                          >
                            • {g}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>

          {/* Pro Tips */}
          {roadmap.tips?.length > 0 && (
            <div
              className="
        rounded-[32px]
        border border-yellow-200
        dark:border-yellow-800
        bg-gradient-to-r
        from-yellow-50
        to-orange-50
        dark:from-yellow-900/20
        dark:to-orange-900/20
        p-8
        shadow-xl
      "
            >
              <h3 className="flex items-center gap-2 text-xl font-bold text-yellow-700 dark:text-yellow-300 mb-5">
                <Lightbulb size={22} />
                Pro Tips
              </h3>

              <div className="space-y-3">
                {roadmap.tips.map((tip, i) => (
                  <div
                    key={i}
                    className="
              rounded-2xl
              bg-white/70
              dark:bg-dark-200/50
              p-4
            "
                  >
                    💡 {tip}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Regenerate Button */}
          <button
            onClick={() => setRoadmap(null)}
            className="
      w-full
      h-14
      rounded-2xl
      bg-gradient-to-r
      from-indigo-600
      to-purple-600
      text-white
      font-semibold
      shadow-xl
      hover:shadow-2xl
      transition-all
    "
          >
            Generate New Roadmap
          </button>
        </motion.div>
      )}
    </div>
  );
};

export default Roadmap;
