const path = require("path");
const mongoose = require("mongoose");
const dotenv = require("dotenv");
const bcrypt = require("bcryptjs");

dotenv.config({ path: path.join(__dirname, "../.env") });

const User = require("../models/User");
const Question = require("../models/Question");
const Quiz = require("../models/Quiz");

const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ MongoDB Connected for seeding...");
  } catch (error) {
    console.error("❌ MongoDB Connection Error:", error.message);
    process.exit(1);
  }
};

// ─── USERS ───────────────────────────────────────────────
const users = [
  {
    name: "Admin User",
    email: "admin@placeprep.com",
    password: "admin123",
    role: "admin",
  },
  {
    name: "Rahul Sharma",
    email: "rahul@student.com",
    password: "student123",
    role: "student",
  },
  {
    name: "Priya Singh",
    email: "priya@student.com",
    password: "student123",
    role: "student",
  },
  {
    name: "Arjun Patel",
    email: "arjun@student.com",
    password: "student123",
    role: "student",
  },
  {
    name: "Sneha Reddy",
    email: "sneha@student.com",
    password: "student123",
    role: "student",
  },
  {
    name: "Kiran Kumar",
    email: "kiran@student.com",
    password: "student123",
    role: "student",
  },
];

// ─── QUESTIONS ───────────────────────────────────────────
const questions = [
  // DSA
  {
    text: "What is the time complexity of binary search?",
    type: "mcq",
    options: [
      { label: "A", value: "O(n)" },
      { label: "B", value: "O(log n)" },
      { label: "C", value: "O(n log n)" },
      { label: "D", value: "O(1)" },
    ],
    answer: "O(log n)",
    explanation:
      "Binary search divides the array in half each time, giving O(log n) complexity.",
    difficulty: "easy",
    category: "DSA",
    tags: ["searching", "algorithms"],
  },
  {
    text: "Which data structure uses LIFO order?",
    type: "mcq",
    options: [
      { label: "A", value: "Queue" },
      { label: "B", value: "Stack" },
      { label: "C", value: "Linked List" },
      { label: "D", value: "Tree" },
    ],
    answer: "Stack",
    explanation: "Stack follows Last In First Out (LIFO) principle.",
    difficulty: "easy",
    category: "DSA",
    tags: ["stack", "data structures"],
  },
  {
    text: "What is the worst case time complexity of QuickSort?",
    type: "mcq",
    options: [
      { label: "A", value: "O(n log n)" },
      { label: "B", value: "O(n)" },
      { label: "C", value: "O(n²)" },
      { label: "D", value: "O(log n)" },
    ],
    answer: "O(n²)",
    explanation:
      "QuickSort worst case occurs when pivot is always the smallest or largest element.",
    difficulty: "medium",
    category: "DSA",
    tags: ["sorting", "algorithms"],
  },
  {
    text: "Which traversal of a BST gives sorted output?",
    type: "mcq",
    options: [
      { label: "A", value: "Preorder" },
      { label: "B", value: "Postorder" },
      { label: "C", value: "Inorder" },
      { label: "D", value: "Level order" },
    ],
    answer: "Inorder",
    explanation:
      "Inorder traversal (Left → Root → Right) of BST gives sorted ascending order.",
    difficulty: "medium",
    category: "DSA",
    tags: ["trees", "BST"],
  },
  {
    text: "What is the space complexity of merge sort?",
    type: "mcq",
    options: [
      { label: "A", value: "O(1)" },
      { label: "B", value: "O(log n)" },
      { label: "C", value: "O(n)" },
      { label: "D", value: "O(n²)" },
    ],
    answer: "O(n)",
    explanation:
      "Merge sort requires O(n) extra space for the temporary arrays during merging.",
    difficulty: "medium",
    category: "DSA",
    tags: ["sorting", "space complexity"],
  },
  {
    text: "Which data structure is used for BFS traversal?",
    type: "mcq",
    options: [
      { label: "A", value: "Stack" },
      { label: "B", value: "Queue" },
      { label: "C", value: "Heap" },
      { label: "D", value: "Tree" },
    ],
    answer: "Queue",
    explanation: "Breadth First Search uses a Queue.",
    difficulty: "easy",
    category: "DSA",
    tags: ["graph", "bfs"],
  },
  {
    text: "Which data structure is used for DFS traversal?",
    type: "mcq",
    options: [
      { label: "A", value: "Queue" },
      { label: "B", value: "Stack" },
      { label: "C", value: "Array" },
      { label: "D", value: "Heap" },
    ],
    answer: "Stack",
    explanation: "Depth First Search uses a Stack.",
    difficulty: "easy",
    category: "DSA",
    tags: ["graph", "dfs"],
  },
  {
    text: "What is the worst case time complexity of linear search?",
    type: "mcq",
    options: [
      { label: "A", value: "O(1)" },
      { label: "B", value: "O(log n)" },
      { label: "C", value: "O(n)" },
      { label: "D", value: "O(n log n)" },
    ],
    answer: "O(n)",
    explanation: "Linear search may traverse all elements.",
    difficulty: "easy",
    category: "DSA",
    tags: ["searching"],
  },
  {
    text: "Which data structure allows insertion and deletion at both ends?",
    type: "mcq",
    options: [
      { label: "A", value: "Stack" },
      { label: "B", value: "Queue" },
      { label: "C", value: "Deque" },
      { label: "D", value: "Heap" },
    ],
    answer: "Deque",
    explanation: "Deque supports insertion and deletion from both ends.",
    difficulty: "medium",
    category: "DSA",
    tags: ["deque"],
  },
  {
    text: "What is the height of a balanced binary tree with n nodes?",
    type: "mcq",
    options: [
      { label: "A", value: "O(n)" },
      { label: "B", value: "O(log n)" },
      { label: "C", value: "O(n log n)" },
      { label: "D", value: "O(1)" },
    ],
    answer: "O(log n)",
    explanation: "Balanced binary trees maintain logarithmic height.",
    difficulty: "medium",
    category: "DSA",
    tags: ["tree"],
  },
  {
    text: "Which sorting algorithm is stable?",
    type: "mcq",
    options: [
      { label: "A", value: "Quick Sort" },
      { label: "B", value: "Heap Sort" },
      { label: "C", value: "Merge Sort" },
      { label: "D", value: "Selection Sort" },
    ],
    answer: "Merge Sort",
    explanation: "Merge Sort preserves the order of equal elements.",
    difficulty: "medium",
    category: "DSA",
    tags: ["sorting"],
  },
  {
    text: "Which data structure is best for implementing priority queues?",
    type: "mcq",
    options: [
      { label: "A", value: "Heap" },
      { label: "B", value: "Array" },
      { label: "C", value: "Stack" },
      { label: "D", value: "Linked List" },
    ],
    answer: "Heap",
    explanation: "Heap provides efficient priority queue operations.",
    difficulty: "easy",
    category: "DSA",
    tags: ["heap"],
  },
  {
    text: "What is the time complexity of inserting into a Binary Search Tree in average case?",
    type: "mcq",
    options: [
      { label: "A", value: "O(log n)" },
      { label: "B", value: "O(n)" },
      { label: "C", value: "O(1)" },
      { label: "D", value: "O(n log n)" },
    ],
    answer: "O(log n)",
    explanation: "Average insertion in BST takes O(log n).",
    difficulty: "medium",
    category: "DSA",
    tags: ["bst"],
  },
  {
    text: "Which traversal visits Root → Left → Right?",
    type: "mcq",
    options: [
      { label: "A", value: "Inorder" },
      { label: "B", value: "Postorder" },
      { label: "C", value: "Preorder" },
      { label: "D", value: "Level Order" },
    ],
    answer: "Preorder",
    explanation: "Preorder traversal follows Root → Left → Right.",
    difficulty: "easy",
    category: "DSA",
    tags: ["tree"],
  },
  {
    text: "Which algorithm is used to find the shortest path in a weighted graph?",
    type: "mcq",
    options: [
      { label: "A", value: "DFS" },
      { label: "B", value: "BFS" },
      { label: "C", value: "Dijkstra" },
      { label: "D", value: "Binary Search" },
    ],
    answer: "Dijkstra",
    explanation:
      "Dijkstra's algorithm finds shortest paths in weighted graphs.",
    difficulty: "hard",
    category: "DSA",
    tags: ["graph", "shortest-path"],
  },
  {
    text: "Which data structure is used in recursion?",
    type: "mcq",
    options: [
      { label: "A", value: "Queue" },
      { label: "B", value: "Heap" },
      { label: "C", value: "Stack" },
      { label: "D", value: "Tree" },
    ],
    answer: "Stack",
    explanation: "Function calls are managed using the call stack.",
    difficulty: "easy",
    category: "DSA",
    tags: ["recursion", "stack"],
  },
  {
    text: "Which sorting algorithm has the best average-case performance?",
    type: "mcq",
    options: [
      { label: "A", value: "Bubble Sort" },
      { label: "B", value: "Merge Sort" },
      { label: "C", value: "Insertion Sort" },
      { label: "D", value: "Selection Sort" },
    ],
    answer: "Merge Sort",
    explanation: "Merge Sort performs in O(n log n) average case.",
    difficulty: "medium",
    category: "DSA",
    tags: ["sorting"],
  },
  {
    text: "What is the maximum number of children a binary tree node can have?",
    type: "mcq",
    options: [
      { label: "A", value: "1" },
      { label: "B", value: "2" },
      { label: "C", value: "3" },
      { label: "D", value: "Unlimited" },
    ],
    answer: "2",
    explanation: "Each binary tree node can have at most two children.",
    difficulty: "easy",
    category: "DSA",
    tags: ["tree"],
  },
  {
    text: "Which algorithm is used to detect cycles in a graph?",
    type: "mcq",
    options: [
      { label: "A", value: "DFS" },
      { label: "B", value: "Binary Search" },
      { label: "C", value: "Merge Sort" },
      { label: "D", value: "Heap Sort" },
    ],
    answer: "DFS",
    explanation: "DFS can be used to detect cycles in graphs.",
    difficulty: "medium",
    category: "DSA",
    tags: ["graph"],
  },
  {
    text: "What is the time complexity of accessing an element in an array?",
    type: "mcq",
    options: [
      { label: "A", value: "O(1)" },
      { label: "B", value: "O(log n)" },
      { label: "C", value: "O(n)" },
      { label: "D", value: "O(n log n)" },
    ],
    answer: "O(1)",
    explanation: "Arrays provide constant time random access.",
    difficulty: "easy",
    category: "DSA",
    tags: ["array"],
  },
  {
    text: "Which data structure is used in BFS?",
    type: "mcq",
    options: [
      { label: "A", value: "Queue" },
      { label: "B", value: "Stack" },
      { label: "C", value: "Heap" },
      { label: "D", value: "Linked List" },
    ],
    answer: "Queue",
    explanation: "BFS explores level by level using a queue.",
    difficulty: "easy",
    category: "DSA",
    tags: ["graph", "bfs"],
  },
  {
    text: "Which searching algorithm requires sorted data?",
    type: "mcq",
    options: [
      { label: "A", value: "Linear Search" },
      { label: "B", value: "Binary Search" },
      { label: "C", value: "DFS" },
      { label: "D", value: "BFS" },
    ],
    answer: "Binary Search",
    explanation: "Binary Search works only on sorted collections.",
    difficulty: "easy",
    category: "DSA",
    tags: ["searching"],
  },
  {
    text: "What is the worst-case time complexity of Bubble Sort?",
    type: "mcq",
    options: [
      { label: "A", value: "O(n)" },
      { label: "B", value: "O(log n)" },
      { label: "C", value: "O(n²)" },
      { label: "D", value: "O(n log n)" },
    ],
    answer: "O(n²)",
    explanation: "Bubble Sort compares each element repeatedly.",
    difficulty: "easy",
    category: "DSA",
    tags: ["sorting"],
  },
  {
    text: "Which traversal uses a queue internally?",
    type: "mcq",
    options: [
      { label: "A", value: "Preorder" },
      { label: "B", value: "Postorder" },
      { label: "C", value: "Level Order" },
      { label: "D", value: "Inorder" },
    ],
    answer: "Level Order",
    explanation: "Level order traversal uses a queue.",
    difficulty: "medium",
    category: "DSA",
    tags: ["tree"],
  },
  {
    text: "What is a complete binary tree?",
    type: "mcq",
    options: [
      { label: "A", value: "Every node has two children" },
      { label: "B", value: "All levels filled except possibly last" },
      { label: "C", value: "Every node has one child" },
      { label: "D", value: "Only root exists" },
    ],
    answer: "All levels filled except possibly last",
    explanation: "Complete binary trees fill nodes left to right.",
    difficulty: "medium",
    category: "DSA",
    tags: ["tree"],
  },
  {
    text: "Which data structure is best for implementing undo operations?",
    type: "mcq",
    options: [
      { label: "A", value: "Queue" },
      { label: "B", value: "Heap" },
      { label: "C", value: "Stack" },
      { label: "D", value: "Graph" },
    ],
    answer: "Stack",
    explanation: "Undo functionality follows LIFO order.",
    difficulty: "easy",
    category: "DSA",
    tags: ["stack"],
  },
  {
    text: "What is the root node in a tree?",
    type: "mcq",
    options: [
      { label: "A", value: "Node with no children" },
      { label: "B", value: "Topmost node" },
      { label: "C", value: "Last node" },
      { label: "D", value: "Middle node" },
    ],
    answer: "Topmost node",
    explanation: "The root is the starting node of a tree.",
    difficulty: "easy",
    category: "DSA",
    tags: ["tree"],
  },
  {
    text: "Which data structure allows fast insertion and deletion?",
    type: "mcq",
    options: [
      { label: "A", value: "Array" },
      { label: "B", value: "Linked List" },
      { label: "C", value: "Stack" },
      { label: "D", value: "Queue" },
    ],
    answer: "Linked List",
    explanation: "Linked lists support efficient insertions and deletions.",
    difficulty: "medium",
    category: "DSA",
    tags: ["linked-list"],
  },
  {
    text: "Which graph algorithm is used for Minimum Spanning Tree?",
    type: "mcq",
    options: [
      { label: "A", value: "Kruskal" },
      { label: "B", value: "DFS" },
      { label: "C", value: "Binary Search" },
      { label: "D", value: "Merge Sort" },
    ],
    answer: "Kruskal",
    explanation: "Kruskal's algorithm finds MST in weighted graphs.",
    difficulty: "hard",
    category: "DSA",
    tags: ["graph", "mst"],
  },
  {
    text: "What is the time complexity of heap insertion?",
    type: "mcq",
    options: [
      { label: "A", value: "O(1)" },
      { label: "B", value: "O(log n)" },
      { label: "C", value: "O(n)" },
      { label: "D", value: "O(n log n)" },
    ],
    answer: "O(log n)",
    explanation: "Heap insertion requires heapify-up operation.",
    difficulty: "medium",
    category: "DSA",
    tags: ["heap"],
  },

  // OS
  {
    text: "What is a deadlock in operating systems?",
    type: "mcq",
    options: [
      { label: "A", value: "A process waiting for CPU" },
      {
        label: "B",
        value: "Two or more processes waiting indefinitely for each other",
      },
      { label: "C", value: "A process using 100% CPU" },
      { label: "D", value: "Memory overflow error" },
    ],
    answer: "Two or more processes waiting indefinitely for each other",
    explanation:
      "Deadlock occurs when processes are blocked forever, each waiting for a resource held by another.",
    difficulty: "medium",
    category: "OS",
    tags: ["deadlock", "processes"],
  },
  {
    text: "Which page replacement algorithm suffers from Belady's anomaly?",
    type: "mcq",
    options: [
      { label: "A", value: "LRU" },
      { label: "B", value: "Optimal" },
      { label: "C", value: "FIFO" },
      { label: "D", value: "LFU" },
    ],
    answer: "FIFO",
    explanation:
      "FIFO can have more page faults with more frames — this is Belady's anomaly.",
    difficulty: "hard",
    category: "OS",
    tags: ["memory management", "page replacement"],
  },
  {
    text: "What is a context switch?",
    type: "mcq",
    options: [
      { label: "A", value: "Switching between two programs by the user" },
      {
        label: "B",
        value: "Saving and restoring state of a process so CPU can be shared",
      },
      { label: "C", value: "Switching the OS kernel" },
      { label: "D", value: "Moving data from RAM to disk" },
    ],
    answer: "Saving and restoring state of a process so CPU can be shared",
    explanation:
      "Context switch saves the state of the current process and loads the saved state of another.",
    difficulty: "easy",
    category: "OS",
    tags: ["scheduling", "processes"],
  },
  {
    text: "Which scheduling algorithm gives the minimum average waiting time?",
    type: "mcq",
    options: [
      { label: "A", value: "FCFS" },
      { label: "B", value: "Round Robin" },
      { label: "C", value: "SJF" },
      { label: "D", value: "Priority Scheduling" },
    ],
    answer: "SJF",
    explanation: "Shortest Job First minimizes average waiting time.",
    difficulty: "medium",
    category: "OS",
    tags: ["cpu-scheduling"],
  },
  {
    text: "What is thrashing in Operating Systems?",
    type: "mcq",
    options: [
      { label: "A", value: "CPU overheating" },
      { label: "B", value: "Excessive paging activity" },
      { label: "C", value: "Disk failure" },
      { label: "D", value: "Process termination" },
    ],
    answer: "Excessive paging activity",
    explanation:
      "Thrashing occurs when the system spends more time paging than executing.",
    difficulty: "hard",
    category: "OS",
    tags: ["memory-management"],
  },
  {
    text: "Which memory is fastest?",
    type: "mcq",
    options: [
      { label: "A", value: "RAM" },
      { label: "B", value: "Cache" },
      { label: "C", value: "Hard Disk" },
      { label: "D", value: "ROM" },
    ],
    answer: "Cache",
    explanation: "Cache memory is faster than RAM and storage devices.",
    difficulty: "easy",
    category: "OS",
    tags: ["memory"],
  },
  {
    text: "What is the purpose of a semaphore?",
    type: "mcq",
    options: [
      { label: "A", value: "Memory allocation" },
      { label: "B", value: "Process synchronization" },
      { label: "C", value: "File storage" },
      { label: "D", value: "CPU scheduling" },
    ],
    answer: "Process synchronization",
    explanation: "Semaphores are used to coordinate process execution.",
    difficulty: "medium",
    category: "OS",
    tags: ["synchronization"],
  },
  {
    text: "Which of the following is not a necessary condition for deadlock?",
    type: "mcq",
    options: [
      { label: "A", value: "Mutual Exclusion" },
      { label: "B", value: "Hold and Wait" },
      { label: "C", value: "Preemption" },
      { label: "D", value: "Circular Wait" },
    ],
    answer: "Preemption",
    explanation: "No Preemption is a deadlock condition, not Preemption.",
    difficulty: "hard",
    category: "OS",
    tags: ["deadlock"],
  },
  {
    text: "Which scheduling algorithm is preemptive?",
    type: "mcq",
    options: [
      { label: "A", value: "FCFS" },
      { label: "B", value: "SJF" },
      { label: "C", value: "Round Robin" },
      { label: "D", value: "None" },
    ],
    answer: "Round Robin",
    explanation: "Round Robin uses time slices and is preemptive.",
    difficulty: "easy",
    category: "OS",
    tags: ["cpu-scheduling"],
  },
  {
    text: "What is virtual memory?",
    type: "mcq",
    options: [
      { label: "A", value: "Extra RAM" },
      {
        label: "B",
        value: "Memory management technique using disk as extension of RAM",
      },
      { label: "C", value: "Cache memory" },
      { label: "D", value: "CPU register" },
    ],
    answer: "Memory management technique using disk as extension of RAM",
    explanation: "Virtual memory extends available memory using disk storage.",
    difficulty: "medium",
    category: "OS",
    tags: ["memory"],
  },
  {
    text: "Which OS component manages files?",
    type: "mcq",
    options: [
      { label: "A", value: "Process Manager" },
      { label: "B", value: "File System" },
      { label: "C", value: "CPU Scheduler" },
      { label: "D", value: "Semaphore" },
    ],
    answer: "File System",
    explanation:
      "The file system organizes and manages files on storage devices.",
    difficulty: "easy",
    category: "OS",
    tags: ["file-system"],
  },
  {
    text: "What is the purpose of paging?",
    type: "mcq",
    options: [
      { label: "A", value: "Increase CPU speed" },
      { label: "B", value: "Reduce fragmentation" },
      { label: "C", value: "Increase cache size" },
      { label: "D", value: "Manage files" },
    ],
    answer: "Reduce fragmentation",
    explanation: "Paging eliminates external fragmentation.",
    difficulty: "medium",
    category: "OS",
    tags: ["paging"],
  },
  {
    text: "Which state comes after Ready state?",
    type: "mcq",
    options: [
      { label: "A", value: "Running" },
      { label: "B", value: "Waiting" },
      { label: "C", value: "Terminated" },
      { label: "D", value: "Blocked" },
    ],
    answer: "Running",
    explanation:
      "The scheduler selects a process from Ready state to Running state.",
    difficulty: "easy",
    category: "OS",
    tags: ["process-state"],
  },

  // DBMS
  {
    text: "Which normal form eliminates transitive dependencies?",
    type: "mcq",
    options: [
      { label: "A", value: "1NF" },
      { label: "B", value: "2NF" },
      { label: "C", value: "3NF" },
      { label: "D", value: "BCNF" },
    ],
    answer: "3NF",
    explanation:
      "3NF eliminates transitive dependencies where non-key attributes depend on other non-key attributes.",
    difficulty: "medium",
    category: "DBMS",
    tags: ["normalization", "3NF"],
  },
  {
    text: "What does ACID stand for in databases?",
    type: "mcq",
    options: [
      { label: "A", value: "Atomicity, Consistency, Isolation, Durability" },
      { label: "B", value: "Accuracy, Consistency, Integrity, Durability" },
      { label: "C", value: "Atomicity, Concurrency, Isolation, Dependency" },
      { label: "D", value: "Accuracy, Concurrency, Integrity, Dependency" },
    ],
    answer: "Atomicity, Consistency, Isolation, Durability",
    explanation:
      "ACID properties ensure reliable processing of database transactions.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["transactions", "ACID"],
  },
  {
    text: "What is the difference between DELETE and TRUNCATE?",
    type: "mcq",
    options: [
      { label: "A", value: "No difference" },
      {
        label: "B",
        value: "DELETE removes all rows, TRUNCATE removes specific rows",
      },
      { label: "C", value: "DELETE can be rolled back, TRUNCATE cannot" },
      { label: "D", value: "TRUNCATE is slower than DELETE" },
    ],
    answer: "DELETE can be rolled back, TRUNCATE cannot",
    explanation:
      "DELETE is a DML operation that can be rolled back. TRUNCATE is DDL and cannot be rolled back.",
    difficulty: "medium",
    category: "DBMS",
    tags: ["SQL", "DDL", "DML"],
  },
  // DBMS Questions (20)

  {
    text: "Which SQL command is used to retrieve data from a database?",
    type: "mcq",
    options: [
      { label: "A", value: "INSERT" },
      { label: "B", value: "UPDATE" },
      { label: "C", value: "SELECT" },
      { label: "D", value: "DELETE" },
    ],
    answer: "SELECT",
    explanation: "SELECT is used to retrieve records from a table.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["sql"],
  },

  {
    text: "What is a Primary Key?",
    type: "mcq",
    options: [
      { label: "A", value: "A duplicated field" },
      { label: "B", value: "A unique identifier for each record" },
      { label: "C", value: "A foreign reference" },
      { label: "D", value: "An indexed column only" },
    ],
    answer: "A unique identifier for each record",
    explanation: "Primary Key uniquely identifies every row in a table.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["keys"],
  },

  {
    text: "Which key is used to establish relationships between tables?",
    type: "mcq",
    options: [
      { label: "A", value: "Primary Key" },
      { label: "B", value: "Candidate Key" },
      { label: "C", value: "Foreign Key" },
      { label: "D", value: "Composite Key" },
    ],
    answer: "Foreign Key",
    explanation: "Foreign Keys connect related tables.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["keys"],
  },

  {
    text: "What does SQL stand for?",
    type: "mcq",
    options: [
      { label: "A", value: "Structured Query Language" },
      { label: "B", value: "Simple Query Language" },
      { label: "C", value: "System Query Language" },
      { label: "D", value: "Server Query Language" },
    ],
    answer: "Structured Query Language",
    explanation: "SQL is used to manage relational databases.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["sql"],
  },

  {
    text: "Which JOIN returns all matching records from both tables?",
    type: "mcq",
    options: [
      { label: "A", value: "INNER JOIN" },
      { label: "B", value: "LEFT JOIN" },
      { label: "C", value: "RIGHT JOIN" },
      { label: "D", value: "FULL OUTER JOIN" },
    ],
    answer: "FULL OUTER JOIN",
    explanation:
      "FULL OUTER JOIN returns matching and non-matching rows from both tables.",
    difficulty: "medium",
    category: "DBMS",
    tags: ["joins"],
  },

  {
    text: "What is normalization?",
    type: "mcq",
    options: [
      { label: "A", value: "Data duplication process" },
      { label: "B", value: "Data organization to reduce redundancy" },
      { label: "C", value: "Data backup process" },
      { label: "D", value: "Data encryption" },
    ],
    answer: "Data organization to reduce redundancy",
    explanation:
      "Normalization reduces data redundancy and improves consistency.",
    difficulty: "medium",
    category: "DBMS",
    tags: ["normalization"],
  },

  {
    text: "Which normal form removes partial dependency?",
    type: "mcq",
    options: [
      { label: "A", value: "1NF" },
      { label: "B", value: "2NF" },
      { label: "C", value: "3NF" },
      { label: "D", value: "BCNF" },
    ],
    answer: "2NF",
    explanation: "2NF eliminates partial dependency.",
    difficulty: "medium",
    category: "DBMS",
    tags: ["normalization"],
  },

  {
    text: "Which SQL clause is used to filter rows?",
    type: "mcq",
    options: [
      { label: "A", value: "ORDER BY" },
      { label: "B", value: "GROUP BY" },
      { label: "C", value: "WHERE" },
      { label: "D", value: "HAVING" },
    ],
    answer: "WHERE",
    explanation: "WHERE filters rows before grouping.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["sql"],
  },

  {
    text: "Which SQL function returns the total number of records?",
    type: "mcq",
    options: [
      { label: "A", value: "SUM()" },
      { label: "B", value: "AVG()" },
      { label: "C", value: "COUNT()" },
      { label: "D", value: "TOTAL()" },
    ],
    answer: "COUNT()",
    explanation: "COUNT() counts rows in a table.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["aggregate"],
  },

  {
    text: "What is a Candidate Key?",
    type: "mcq",
    options: [
      { label: "A", value: "A possible Primary Key" },
      { label: "B", value: "Duplicate Key" },
      { label: "C", value: "Foreign Key" },
      { label: "D", value: "Secondary Key" },
    ],
    answer: "A possible Primary Key",
    explanation: "Candidate Keys are eligible to become Primary Keys.",
    difficulty: "medium",
    category: "DBMS",
    tags: ["keys"],
  },

  {
    text: "Which command removes all rows but keeps the table structure?",
    type: "mcq",
    options: [
      { label: "A", value: "DELETE" },
      { label: "B", value: "DROP" },
      { label: "C", value: "TRUNCATE" },
      { label: "D", value: "REMOVE" },
    ],
    answer: "TRUNCATE",
    explanation: "TRUNCATE removes all rows while retaining structure.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["sql"],
  },

  {
    text: "Which SQL clause is used to sort data?",
    type: "mcq",
    options: [
      { label: "A", value: "GROUP BY" },
      { label: "B", value: "ORDER BY" },
      { label: "C", value: "WHERE" },
      { label: "D", value: "HAVING" },
    ],
    answer: "ORDER BY",
    explanation: "ORDER BY sorts records in ascending or descending order.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["sql"],
  },

  {
    text: "What is the purpose of an index?",
    type: "mcq",
    options: [
      { label: "A", value: "Increase storage" },
      { label: "B", value: "Improve query performance" },
      { label: "C", value: "Delete records" },
      { label: "D", value: "Create backups" },
    ],
    answer: "Improve query performance",
    explanation: "Indexes speed up data retrieval.",
    difficulty: "medium",
    category: "DBMS",
    tags: ["index"],
  },

  {
    text: "Which JOIN returns only matching records?",
    type: "mcq",
    options: [
      { label: "A", value: "LEFT JOIN" },
      { label: "B", value: "RIGHT JOIN" },
      { label: "C", value: "INNER JOIN" },
      { label: "D", value: "FULL JOIN" },
    ],
    answer: "INNER JOIN",
    explanation: "INNER JOIN returns only matching rows.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["joins"],
  },

  {
    text: "What is denormalization?",
    type: "mcq",
    options: [
      { label: "A", value: "Removing redundancy" },
      { label: "B", value: "Adding redundancy for performance" },
      { label: "C", value: "Deleting tables" },
      { label: "D", value: "Creating indexes" },
    ],
    answer: "Adding redundancy for performance",
    explanation: "Denormalization improves read performance.",
    difficulty: "hard",
    category: "DBMS",
    tags: ["normalization"],
  },

  {
    text: "Which SQL statement adds new records?",
    type: "mcq",
    options: [
      { label: "A", value: "UPDATE" },
      { label: "B", value: "INSERT" },
      { label: "C", value: "SELECT" },
      { label: "D", value: "ALTER" },
    ],
    answer: "INSERT",
    explanation: "INSERT adds new rows into a table.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["sql"],
  },

  {
    text: "Which command modifies existing records?",
    type: "mcq",
    options: [
      { label: "A", value: "INSERT" },
      { label: "B", value: "UPDATE" },
      { label: "C", value: "DELETE" },
      { label: "D", value: "ALTER" },
    ],
    answer: "UPDATE",
    explanation: "UPDATE changes existing data.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["sql"],
  },

  {
    text: "What is a transaction?",
    type: "mcq",
    options: [
      { label: "A", value: "A database backup" },
      { label: "B", value: "A logical unit of work" },
      { label: "C", value: "An index" },
      { label: "D", value: "A table join" },
    ],
    answer: "A logical unit of work",
    explanation: "Transactions ensure reliable database operations.",
    difficulty: "medium",
    category: "DBMS",
    tags: ["transaction"],
  },

  {
    text: "Which ACID property ensures completed transactions remain permanent?",
    type: "mcq",
    options: [
      { label: "A", value: "Atomicity" },
      { label: "B", value: "Consistency" },
      { label: "C", value: "Isolation" },
      { label: "D", value: "Durability" },
    ],
    answer: "Durability",
    explanation: "Durability guarantees permanent storage after commit.",
    difficulty: "medium",
    category: "DBMS",
    tags: ["acid"],
  },

  {
    text: "Which SQL command permanently removes a table?",
    type: "mcq",
    options: [
      { label: "A", value: "DELETE" },
      { label: "B", value: "REMOVE" },
      { label: "C", value: "TRUNCATE" },
      { label: "D", value: "DROP" },
    ],
    answer: "DROP",
    explanation: "DROP removes the entire table structure and data.",
    difficulty: "easy",
    category: "DBMS",
    tags: ["sql"],
  },

  // Aptitude
  {
    text: "If a train travels 60 km in 1 hour, how long will it take to travel 150 km?",
    type: "mcq",
    options: [
      { label: "A", value: "2 hours" },
      { label: "B", value: "2.5 hours" },
      { label: "C", value: "3 hours" },
      { label: "D", value: "1.5 hours" },
    ],
    answer: "2.5 hours",
    explanation: "Speed = 60 km/h. Time = Distance/Speed = 150/60 = 2.5 hours.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["speed", "distance", "time"],
  },
  {
    text: "What is 15% of 200?",
    type: "mcq",
    options: [
      { label: "A", value: "20" },
      { label: "B", value: "25" },
      { label: "C", value: "30" },
      { label: "D", value: "35" },
    ],
    answer: "30",
    explanation: "15% of 200 = (15/100) × 200 = 30.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["percentage", "arithmetic"],
  },
  {
    text: "A can do a work in 10 days, B in 15 days. How many days together?",
    type: "mcq",
    options: [
      { label: "A", value: "5 days" },
      { label: "B", value: "6 days" },
      { label: "C", value: "8 days" },
      { label: "D", value: "12 days" },
    ],
    answer: "6 days",
    explanation:
      "Combined rate = 1/10 + 1/15 = 3/30 + 2/30 = 5/30 = 1/6. So together = 6 days.",
    difficulty: "medium",
    category: "Aptitude",
    tags: ["work", "time"],
  },
  {
    text: "What is 25% of 400?",
    type: "mcq",
    options: [
      { label: "A", value: "50" },
      { label: "B", value: "75" },
      { label: "C", value: "100" },
      { label: "D", value: "125" },
    ],
    answer: "100",
    explanation: "25% of 400 = 100.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["percentage"],
  },
  {
    text: "A train travels 120 km in 2 hours. What is its speed?",
    type: "mcq",
    options: [
      { label: "A", value: "50 km/h" },
      { label: "B", value: "60 km/h" },
      { label: "C", value: "70 km/h" },
      { label: "D", value: "80 km/h" },
    ],
    answer: "60 km/h",
    explanation: "Speed = Distance / Time = 120/2 = 60 km/h.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["speed-distance-time"],
  },
  {
    text: "The average of 10, 20, 30, 40, 50 is?",
    type: "mcq",
    options: [
      { label: "A", value: "25" },
      { label: "B", value: "30" },
      { label: "C", value: "35" },
      { label: "D", value: "40" },
    ],
    answer: "30",
    explanation: "Average = Sum / Count = 150 / 5 = 30.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["average"],
  },
  {
    text: "If CP = ₹500 and SP = ₹600, profit percentage is?",
    type: "mcq",
    options: [
      { label: "A", value: "10%" },
      { label: "B", value: "15%" },
      { label: "C", value: "20%" },
      { label: "D", value: "25%" },
    ],
    answer: "20%",
    explanation: "Profit = 100. Profit% = (100/500)*100 = 20%.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["profit-loss"],
  },
  {
    text: "Simple Interest on ₹1000 at 10% for 2 years?",
    type: "mcq",
    options: [
      { label: "A", value: "₹100" },
      { label: "B", value: "₹150" },
      { label: "C", value: "₹200" },
      { label: "D", value: "₹250" },
    ],
    answer: "₹200",
    explanation: "SI = (P×R×T)/100 = 200.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["simple-interest"],
  },
  {
    text: "What is the ratio of 20 to 50?",
    type: "mcq",
    options: [
      { label: "A", value: "2:5" },
      { label: "B", value: "3:5" },
      { label: "C", value: "4:5" },
      { label: "D", value: "1:5" },
    ],
    answer: "2:5",
    explanation: "20:50 = 2:5.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["ratio"],
  },
  {
    text: "A can complete a work in 12 days. How much work can A do in 1 day?",
    type: "mcq",
    options: [
      { label: "A", value: "1/10" },
      { label: "B", value: "1/12" },
      { label: "C", value: "1/15" },
      { label: "D", value: "1/20" },
    ],
    answer: "1/12",
    explanation: "Work done in 1 day = 1/12.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["time-work"],
  },
  {
    text: "What is 20% of 250?",
    type: "mcq",
    options: [
      { label: "A", value: "40" },
      { label: "B", value: "50" },
      { label: "C", value: "60" },
      { label: "D", value: "70" },
    ],
    answer: "50",
    explanation: "20% × 250 = 50.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["percentage"],
  },
  {
    text: "The sum of angles in a triangle is?",
    type: "mcq",
    options: [
      { label: "A", value: "90°" },
      { label: "B", value: "180°" },
      { label: "C", value: "270°" },
      { label: "D", value: "360°" },
    ],
    answer: "180°",
    explanation: "Angles of a triangle always sum to 180°.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["geometry"],
  },
  {
    text: "What is the square root of 625?",
    type: "mcq",
    options: [
      { label: "A", value: "20" },
      { label: "B", value: "25" },
      { label: "C", value: "30" },
      { label: "D", value: "35" },
    ],
    answer: "25",
    explanation: "25 × 25 = 625.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["math"],
  },
  {
    text: "A boat moves at 10 km/h in still water and stream speed is 2 km/h. Downstream speed?",
    type: "mcq",
    options: [
      { label: "A", value: "8 km/h" },
      { label: "B", value: "10 km/h" },
      { label: "C", value: "12 km/h" },
      { label: "D", value: "14 km/h" },
    ],
    answer: "12 km/h",
    explanation: "Downstream = Boat speed + Stream speed.",
    difficulty: "medium",
    category: "Aptitude",
    tags: ["boats-streams"],
  },
  {
    text: "Compound Interest on ₹1000 at 10% for 2 years is?",
    type: "mcq",
    options: [
      { label: "A", value: "₹200" },
      { label: "B", value: "₹210" },
      { label: "C", value: "₹220" },
      { label: "D", value: "₹250" },
    ],
    answer: "₹210",
    explanation: "CI = 1000(1.1²)-1000 = ₹210.",
    difficulty: "medium",
    category: "Aptitude",
    tags: ["compound-interest"],
  },
  {
    text: "Probability of getting a head on a fair coin toss?",
    type: "mcq",
    options: [
      { label: "A", value: "1/4" },
      { label: "B", value: "1/3" },
      { label: "C", value: "1/2" },
      { label: "D", value: "1" },
    ],
    answer: "1/2",
    explanation: "One favorable outcome out of two possible outcomes.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["probability"],
  },
  {
    text: "What is 15 × 15?",
    type: "mcq",
    options: [
      { label: "A", value: "200" },
      { label: "B", value: "225" },
      { label: "C", value: "250" },
      { label: "D", value: "275" },
    ],
    answer: "225",
    explanation: "15 × 15 = 225.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["arithmetic"],
  },
  {
    text: "If 3x = 18, x = ?",
    type: "mcq",
    options: [
      { label: "A", value: "4" },
      { label: "B", value: "5" },
      { label: "C", value: "6" },
      { label: "D", value: "7" },
    ],
    answer: "6",
    explanation: "18 ÷ 3 = 6.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["algebra"],
  },
  {
    text: "A shopkeeper gives 10% discount on ₹1000. Selling price?",
    type: "mcq",
    options: [
      { label: "A", value: "₹800" },
      { label: "B", value: "₹850" },
      { label: "C", value: "₹900" },
      { label: "D", value: "₹950" },
    ],
    answer: "₹900",
    explanation: "10% of 1000 = 100. SP = 900.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["discount"],
  },
  {
    text: "What is 40% of 500?",
    type: "mcq",
    options: [
      { label: "A", value: "150" },
      { label: "B", value: "180" },
      { label: "C", value: "200" },
      { label: "D", value: "220" },
    ],
    answer: "200",
    explanation: "40% × 500 = 200.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["percentage"],
  },
  {
    text: "A person covers 240 km in 4 hours. Speed?",
    type: "mcq",
    options: [
      { label: "A", value: "50 km/h" },
      { label: "B", value: "60 km/h" },
      { label: "C", value: "70 km/h" },
      { label: "D", value: "80 km/h" },
    ],
    answer: "60 km/h",
    explanation: "240 ÷ 4 = 60 km/h.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["speed-distance-time"],
  },
  {
    text: "What is the cube of 5?",
    type: "mcq",
    options: [
      { label: "A", value: "25" },
      { label: "B", value: "75" },
      { label: "C", value: "100" },
      { label: "D", value: "125" },
    ],
    answer: "125",
    explanation: "5³ = 125.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["math"],
  },
  {
    text: "A bag contains 5 red and 5 blue balls. Probability of picking a red ball?",
    type: "mcq",
    options: [
      { label: "A", value: "1/4" },
      { label: "B", value: "1/2" },
      { label: "C", value: "3/4" },
      { label: "D", value: "1" },
    ],
    answer: "1/2",
    explanation: "5 favorable outcomes out of 10 total.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["probability"],
  },
  {
    text: "What is 25% of 400?",
    type: "mcq",
    options: [
      { label: "A", value: "50" },
      { label: "B", value: "75" },
      { label: "C", value: "100" },
      { label: "D", value: "125" },
    ],
    answer: "100",
    explanation: "25% of 400 = 100.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["percentage"],
  },
  {
    text: "A train travels 120 km in 2 hours. What is its speed?",
    type: "mcq",
    options: [
      { label: "A", value: "50 km/h" },
      { label: "B", value: "60 km/h" },
      { label: "C", value: "70 km/h" },
      { label: "D", value: "80 km/h" },
    ],
    answer: "60 km/h",
    explanation: "Speed = Distance / Time = 120/2 = 60 km/h.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["speed-distance-time"],
  },
  {
    text: "The average of 10, 20, 30, 40, 50 is?",
    type: "mcq",
    options: [
      { label: "A", value: "25" },
      { label: "B", value: "30" },
      { label: "C", value: "35" },
      { label: "D", value: "40" },
    ],
    answer: "30",
    explanation: "Average = Sum / Count = 150 / 5 = 30.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["average"],
  },
  {
    text: "If CP = ₹500 and SP = ₹600, profit percentage is?",
    type: "mcq",
    options: [
      { label: "A", value: "10%" },
      { label: "B", value: "15%" },
      { label: "C", value: "20%" },
      { label: "D", value: "25%" },
    ],
    answer: "20%",
    explanation: "Profit = 100. Profit% = (100/500)*100 = 20%.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["profit-loss"],
  },
  {
    text: "Simple Interest on ₹1000 at 10% for 2 years?",
    type: "mcq",
    options: [
      { label: "A", value: "₹100" },
      { label: "B", value: "₹150" },
      { label: "C", value: "₹200" },
      { label: "D", value: "₹250" },
    ],
    answer: "₹200",
    explanation: "SI = (P×R×T)/100 = 200.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["simple-interest"],
  },
  {
    text: "What is the ratio of 20 to 50?",
    type: "mcq",
    options: [
      { label: "A", value: "2:5" },
      { label: "B", value: "3:5" },
      { label: "C", value: "4:5" },
      { label: "D", value: "1:5" },
    ],
    answer: "2:5",
    explanation: "20:50 = 2:5.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["ratio"],
  },
  {
    text: "A can complete a work in 12 days. How much work can A do in 1 day?",
    type: "mcq",
    options: [
      { label: "A", value: "1/10" },
      { label: "B", value: "1/12" },
      { label: "C", value: "1/15" },
      { label: "D", value: "1/20" },
    ],
    answer: "1/12",
    explanation: "Work done in 1 day = 1/12.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["time-work"],
  },
  {
    text: "What is 20% of 250?",
    type: "mcq",
    options: [
      { label: "A", value: "40" },
      { label: "B", value: "50" },
      { label: "C", value: "60" },
      { label: "D", value: "70" },
    ],
    answer: "50",
    explanation: "20% × 250 = 50.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["percentage"],
  },
  {
    text: "The sum of angles in a triangle is?",
    type: "mcq",
    options: [
      { label: "A", value: "90°" },
      { label: "B", value: "180°" },
      { label: "C", value: "270°" },
      { label: "D", value: "360°" },
    ],
    answer: "180°",
    explanation: "Angles of a triangle always sum to 180°.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["geometry"],
  },
  {
    text: "What is the square root of 625?",
    type: "mcq",
    options: [
      { label: "A", value: "20" },
      { label: "B", value: "25" },
      { label: "C", value: "30" },
      { label: "D", value: "35" },
    ],
    answer: "25",
    explanation: "25 × 25 = 625.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["math"],
  },
  {
    text: "A boat moves at 10 km/h in still water and stream speed is 2 km/h. Downstream speed?",
    type: "mcq",
    options: [
      { label: "A", value: "8 km/h" },
      { label: "B", value: "10 km/h" },
      { label: "C", value: "12 km/h" },
      { label: "D", value: "14 km/h" },
    ],
    answer: "12 km/h",
    explanation: "Downstream = Boat speed + Stream speed.",
    difficulty: "medium",
    category: "Aptitude",
    tags: ["boats-streams"],
  },
  {
    text: "Compound Interest on ₹1000 at 10% for 2 years is?",
    type: "mcq",
    options: [
      { label: "A", value: "₹200" },
      { label: "B", value: "₹210" },
      { label: "C", value: "₹220" },
      { label: "D", value: "₹250" },
    ],
    answer: "₹210",
    explanation: "CI = 1000(1.1²)-1000 = ₹210.",
    difficulty: "medium",
    category: "Aptitude",
    tags: ["compound-interest"],
  },
  {
    text: "Probability of getting a head on a fair coin toss?",
    type: "mcq",
    options: [
      { label: "A", value: "1/4" },
      { label: "B", value: "1/3" },
      { label: "C", value: "1/2" },
      { label: "D", value: "1" },
    ],
    answer: "1/2",
    explanation: "One favorable outcome out of two possible outcomes.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["probability"],
  },
  {
    text: "What is 15 × 15?",
    type: "mcq",
    options: [
      { label: "A", value: "200" },
      { label: "B", value: "225" },
      { label: "C", value: "250" },
      { label: "D", value: "275" },
    ],
    answer: "225",
    explanation: "15 × 15 = 225.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["arithmetic"],
  },
  {
    text: "If 3x = 18, x = ?",
    type: "mcq",
    options: [
      { label: "A", value: "4" },
      { label: "B", value: "5" },
      { label: "C", value: "6" },
      { label: "D", value: "7" },
    ],
    answer: "6",
    explanation: "18 ÷ 3 = 6.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["algebra"],
  },
  {
    text: "A shopkeeper gives 10% discount on ₹1000. Selling price?",
    type: "mcq",
    options: [
      { label: "A", value: "₹800" },
      { label: "B", value: "₹850" },
      { label: "C", value: "₹900" },
      { label: "D", value: "₹950" },
    ],
    answer: "₹900",
    explanation: "10% of 1000 = 100. SP = 900.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["discount"],
  },
  {
    text: "What is 40% of 500?",
    type: "mcq",
    options: [
      { label: "A", value: "150" },
      { label: "B", value: "180" },
      { label: "C", value: "200" },
      { label: "D", value: "220" },
    ],
    answer: "200",
    explanation: "40% × 500 = 200.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["percentage"],
  },
  {
    text: "A person covers 240 km in 4 hours. Speed?",
    type: "mcq",
    options: [
      { label: "A", value: "50 km/h" },
      { label: "B", value: "60 km/h" },
      { label: "C", value: "70 km/h" },
      { label: "D", value: "80 km/h" },
    ],
    answer: "60 km/h",
    explanation: "240 ÷ 4 = 60 km/h.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["speed-distance-time"],
  },
  {
    text: "What is the cube of 5?",
    type: "mcq",
    options: [
      { label: "A", value: "25" },
      { label: "B", value: "75" },
      { label: "C", value: "100" },
      { label: "D", value: "125" },
    ],
    answer: "125",
    explanation: "5³ = 125.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["math"],
  },
  {
    text: "A bag contains 5 red and 5 blue balls. Probability of picking a red ball?",
    type: "mcq",
    options: [
      { label: "A", value: "1/4" },
      { label: "B", value: "1/2" },
      { label: "C", value: "3/4" },
      { label: "D", value: "1" },
    ],
    answer: "1/2",
    explanation: "5 favorable outcomes out of 10 total.",
    difficulty: "medium",
    category: "Aptitude",
    tags: ["probability"],
  },
  {
    text: "If the ratio of boys to girls in a class is 3:2 and there are 30 boys, how many girls are there?",
    type: "mcq",
    options: [
      { label: "A", value: "15" },
      { label: "B", value: "20" },
      { label: "C", value: "25" },
      { label: "D", value: "30" },
    ],
    answer: "20",
    explanation: "3:2 = 30:x, so x = 20.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["ratio"],
  },
  {
    text: "The average of first 5 natural numbers is?",
    type: "mcq",
    options: [
      { label: "A", value: "2" },
      { label: "B", value: "2.5" },
      { label: "C", value: "3" },
      { label: "D", value: "3.5" },
    ],
    answer: "3",
    explanation: "Average = (1+2+3+4+5)/5 = 3.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["average"],
  },
  {
    text: "A sum doubles itself in 10 years at simple interest. What is the annual rate?",
    type: "mcq",
    options: [
      { label: "A", value: "5%" },
      { label: "B", value: "10%" },
      { label: "C", value: "15%" },
      { label: "D", value: "20%" },
    ],
    answer: "10%",
    explanation: "SI = Principal in 10 years, so rate = 100/10 = 10%.",
    difficulty: "medium",
    category: "Aptitude",
    tags: ["simple-interest"],
  },
  {
    text: "What is 35% of 800?",
    type: "mcq",
    options: [
      { label: "A", value: "260" },
      { label: "B", value: "280" },
      { label: "C", value: "300" },
      { label: "D", value: "320" },
    ],
    answer: "280",
    explanation: "35% of 800 = 280.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["percentage"],
  },
  {
    text: "A man buys an article for ₹800 and sells it for ₹920. Profit percentage is?",
    type: "mcq",
    options: [
      { label: "A", value: "10%" },
      { label: "B", value: "12%" },
      { label: "C", value: "15%" },
      { label: "D", value: "20%" },
    ],
    answer: "15%",
    explanation: "Profit = 120, Profit% = (120/800)×100 = 15%.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["profit-loss"],
  },
  {
    text: "A train 150m long crosses a pole in 15 seconds. Speed is?",
    type: "mcq",
    options: [
      { label: "A", value: "10 m/s" },
      { label: "B", value: "12 m/s" },
      { label: "C", value: "15 m/s" },
      { label: "D", value: "20 m/s" },
    ],
    answer: "10 m/s",
    explanation: "Speed = Distance/Time = 150/15 = 10 m/s.",
    difficulty: "medium",
    category: "Aptitude",
    tags: ["train-problems"],
  },
  {
    text: "If 12 men can complete a work in 15 days, how many days will 20 men take?",
    type: "mcq",
    options: [
      { label: "A", value: "8" },
      { label: "B", value: "9" },
      { label: "C", value: "10" },
      { label: "D", value: "12" },
    ],
    answer: "9",
    explanation: "Men × Days = Constant → 12×15 = 20×x → x=9.",
    difficulty: "medium",
    category: "Aptitude",
    tags: ["time-work"],
  },
  {
    text: "The probability of getting an even number on a dice is?",
    type: "mcq",
    options: [
      { label: "A", value: "1/6" },
      { label: "B", value: "1/3" },
      { label: "C", value: "1/2" },
      { label: "D", value: "2/3" },
    ],
    answer: "1/2",
    explanation: "Even numbers are 2,4,6. Probability = 3/6 = 1/2.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["probability"],
  },
  {
    text: "What is the next number in the series: 2, 4, 8, 16, ?",
    type: "mcq",
    options: [
      { label: "A", value: "24" },
      { label: "B", value: "30" },
      { label: "C", value: "32" },
      { label: "D", value: "36" },
    ],
    answer: "32",
    explanation: "Each number is multiplied by 2.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["series"],
  },
  {
    text: "A shopkeeper marks an item at ₹1000 and gives 20% discount. Selling price is?",
    type: "mcq",
    options: [
      { label: "A", value: "₹700" },
      { label: "B", value: "₹750" },
      { label: "C", value: "₹800" },
      { label: "D", value: "₹850" },
    ],
    answer: "₹800",
    explanation: "20% discount on ₹1000 = ₹200, SP = ₹800.",
    difficulty: "easy",
    category: "Aptitude",
    tags: ["discount"],
  },
  // HR
  {
    text: "What is your greatest strength?",
    type: "hr",
    options: [
      { label: "A", value: "Technical skills only" },
      { label: "B", value: "Problem solving and teamwork" },
      { label: "C", value: "Working alone" },
      { label: "D", value: "Following instructions only" },
    ],
    answer: "Problem solving and teamwork",
    explanation:
      "Employers value both technical and soft skills like problem solving and collaboration.",
    difficulty: "easy",
    category: "HR",
    tags: ["behavioral", "strengths"],
  },
  {
    text: "Where do you see yourself in 5 years?",
    type: "hr",
    options: [
      { label: "A", value: "In a managerial role with expertise in my domain" },
      { label: "B", value: "Same position as today" },
      { label: "C", value: "I have no plans" },
      { label: "D", value: "Working at a competitor company" },
    ],
    answer: "In a managerial role with expertise in my domain",
    explanation:
      "Showing ambition aligned with company growth is the ideal answer.",
    difficulty: "easy",
    category: "HR",
    tags: ["career goals", "behavioral"],
  },
  // HR Questions (20)

  {
    text: "Tell me about yourself.",
    type: "mcq",
    options: [
      { label: "A", value: "Discuss personal hobbies only" },
      {
        label: "B",
        value:
          "Give a structured introduction about education, skills and goals",
      },
      { label: "C", value: "Talk only about family" },
      { label: "D", value: "Mention weaknesses first" },
    ],
    answer: "Give a structured introduction about education, skills and goals",
    explanation:
      "A professional self-introduction should highlight academics, skills and career goals.",
    difficulty: "easy",
    category: "HR",
    tags: ["introduction"],
  },

  {
    text: "Why do you want to work for our company?",
    type: "mcq",
    options: [
      { label: "A", value: "Because it pays well" },
      { label: "B", value: "Because my friend works here" },
      {
        label: "C",
        value:
          "Because of company values, growth opportunities and role alignment",
      },
      { label: "D", value: "No specific reason" },
    ],
    answer:
      "Because of company values, growth opportunities and role alignment",
    explanation:
      "Employers expect candidates to research the company and role.",
    difficulty: "easy",
    category: "HR",
    tags: ["company"],
  },

  {
    text: "What is your greatest strength?",
    type: "mcq",
    options: [
      { label: "A", value: "Mention a relevant skill with example" },
      { label: "B", value: "Say I have no strengths" },
      { label: "C", value: "Avoid answering" },
      { label: "D", value: "Mention random strengths" },
    ],
    answer: "Mention a relevant skill with example",
    explanation: "Support strengths with real examples.",
    difficulty: "easy",
    category: "HR",
    tags: ["strengths"],
  },

  {
    text: "How should you answer 'What is your weakness?'",
    type: "mcq",
    options: [
      { label: "A", value: "Say you have none" },
      { label: "B", value: "Mention a genuine weakness and improvement plan" },
      { label: "C", value: "Refuse to answer" },
      { label: "D", value: "Blame others" },
    ],
    answer: "Mention a genuine weakness and improvement plan",
    explanation: "Interviewers value self-awareness and improvement.",
    difficulty: "medium",
    category: "HR",
    tags: ["weakness"],
  },

  {
    text: "Where do you see yourself in 5 years?",
    type: "mcq",
    options: [
      { label: "A", value: "Unemployed" },
      {
        label: "B",
        value: "Growing professionally with greater responsibilities",
      },
      { label: "C", value: "Retired" },
      { label: "D", value: "No idea" },
    ],
    answer: "Growing professionally with greater responsibilities",
    explanation: "Show ambition aligned with career growth.",
    difficulty: "easy",
    category: "HR",
    tags: ["career"],
  },

  {
    text: "Why should we hire you?",
    type: "mcq",
    options: [
      { label: "A", value: "I need a job" },
      {
        label: "B",
        value: "I match the required skills and can contribute effectively",
      },
      { label: "C", value: "Because I applied first" },
      { label: "D", value: "No reason" },
    ],
    answer: "I match the required skills and can contribute effectively",
    explanation: "Connect your skills and achievements to the role.",
    difficulty: "medium",
    category: "HR",
    tags: ["hiring"],
  },

  {
    text: "How should you handle workplace conflict?",
    type: "mcq",
    options: [
      { label: "A", value: "Ignore it completely" },
      {
        label: "B",
        value: "Communicate professionally and resolve collaboratively",
      },
      { label: "C", value: "Argue aggressively" },
      { label: "D", value: "Complain publicly" },
    ],
    answer: "Communicate professionally and resolve collaboratively",
    explanation: "Employers value teamwork and communication.",
    difficulty: "medium",
    category: "HR",
    tags: ["conflict"],
  },

  {
    text: "What motivates you at work?",
    type: "mcq",
    options: [
      { label: "A", value: "Learning, growth and meaningful contribution" },
      { label: "B", value: "Nothing" },
      { label: "C", value: "Only salary" },
      { label: "D", value: "Avoiding work" },
    ],
    answer: "Learning, growth and meaningful contribution",
    explanation: "A balanced answer shows long-term commitment.",
    difficulty: "easy",
    category: "HR",
    tags: ["motivation"],
  },

  {
    text: "How do you prioritize multiple tasks?",
    type: "mcq",
    options: [
      { label: "A", value: "Do random tasks first" },
      { label: "B", value: "Prioritize based on urgency and importance" },
      { label: "C", value: "Ignore deadlines" },
      { label: "D", value: "Wait for others" },
    ],
    answer: "Prioritize based on urgency and importance",
    explanation: "Time management is a key workplace skill.",
    difficulty: "medium",
    category: "HR",
    tags: ["time-management"],
  },

  {
    text: "What would you do if you made a mistake at work?",
    type: "mcq",
    options: [
      { label: "A", value: "Hide it" },
      { label: "B", value: "Take responsibility and fix it" },
      { label: "C", value: "Blame colleagues" },
      { label: "D", value: "Ignore it" },
    ],
    answer: "Take responsibility and fix it",
    explanation: "Accountability builds trust.",
    difficulty: "medium",
    category: "HR",
    tags: ["responsibility"],
  },

  {
    text: "What is teamwork?",
    type: "mcq",
    options: [
      { label: "A", value: "Working alone" },
      { label: "B", value: "Collaborating effectively toward a common goal" },
      { label: "C", value: "Delegating everything" },
      { label: "D", value: "Competing internally" },
    ],
    answer: "Collaborating effectively toward a common goal",
    explanation: "Teamwork is essential in organizations.",
    difficulty: "easy",
    category: "HR",
    tags: ["teamwork"],
  },

  {
    text: "How would you handle tight deadlines?",
    type: "mcq",
    options: [
      { label: "A", value: "Panic" },
      { label: "B", value: "Plan, prioritize and communicate effectively" },
      { label: "C", value: "Miss deadlines" },
      { label: "D", value: "Avoid work" },
    ],
    answer: "Plan, prioritize and communicate effectively",
    explanation: "Shows stress management and professionalism.",
    difficulty: "medium",
    category: "HR",
    tags: ["deadlines"],
  },

  {
    text: "What is leadership?",
    type: "mcq",
    options: [
      { label: "A", value: "Giving orders only" },
      { label: "B", value: "Guiding and motivating a team toward goals" },
      { label: "C", value: "Working alone" },
      { label: "D", value: "Controlling others" },
    ],
    answer: "Guiding and motivating a team toward goals",
    explanation: "Leadership involves influence and responsibility.",
    difficulty: "easy",
    category: "HR",
    tags: ["leadership"],
  },

  {
    text: "Why are communication skills important?",
    type: "mcq",
    options: [
      {
        label: "A",
        value: "To avoid misunderstandings and collaborate effectively",
      },
      { label: "B", value: "Not important" },
      { label: "C", value: "Only for managers" },
      { label: "D", value: "Only for meetings" },
    ],
    answer: "To avoid misunderstandings and collaborate effectively",
    explanation: "Communication is critical in every role.",
    difficulty: "easy",
    category: "HR",
    tags: ["communication"],
  },

  {
    text: "What would you do if you disagree with your manager?",
    type: "mcq",
    options: [
      { label: "A", value: "Argue publicly" },
      {
        label: "B",
        value: "Discuss respectfully with facts and professionalism",
      },
      { label: "C", value: "Ignore manager" },
      { label: "D", value: "Quit immediately" },
    ],
    answer: "Discuss respectfully with facts and professionalism",
    explanation: "Professional communication is important.",
    difficulty: "medium",
    category: "HR",
    tags: ["manager"],
  },

  {
    text: "What does professionalism mean?",
    type: "mcq",
    options: [
      { label: "A", value: "Being responsible, ethical and respectful" },
      { label: "B", value: "Wearing formal clothes only" },
      { label: "C", value: "Working overtime daily" },
      { label: "D", value: "Being strict" },
    ],
    answer: "Being responsible, ethical and respectful",
    explanation: "Professionalism includes attitude and conduct.",
    difficulty: "easy",
    category: "HR",
    tags: ["professionalism"],
  },

  {
    text: "How do you handle stress?",
    type: "mcq",
    options: [
      { label: "A", value: "Stay organized and focus on solutions" },
      { label: "B", value: "Panic immediately" },
      { label: "C", value: "Avoid responsibilities" },
      { label: "D", value: "Ignore problems" },
    ],
    answer: "Stay organized and focus on solutions",
    explanation: "Employers value resilience and composure.",
    difficulty: "medium",
    category: "HR",
    tags: ["stress"],
  },

  {
    text: "What is your ideal work environment?",
    type: "mcq",
    options: [
      { label: "A", value: "Collaborative and growth-oriented" },
      { label: "B", value: "No interaction" },
      { label: "C", value: "No deadlines" },
      { label: "D", value: "No responsibilities" },
    ],
    answer: "Collaborative and growth-oriented",
    explanation: "Shows adaptability and teamwork.",
    difficulty: "easy",
    category: "HR",
    tags: ["workplace"],
  },

  {
    text: "How do you learn new skills quickly?",
    type: "mcq",
    options: [
      { label: "A", value: "Practice consistently and seek feedback" },
      { label: "B", value: "Avoid learning" },
      { label: "C", value: "Depend on others" },
      { label: "D", value: "Memorize without understanding" },
    ],
    answer: "Practice consistently and seek feedback",
    explanation: "Continuous learning is highly valued.",
    difficulty: "easy",
    category: "HR",
    tags: ["learning"],
  },

  {
    text: "What is the best way to answer behavioral interview questions?",
    type: "mcq",
    options: [
      { label: "A", value: "Use the STAR method" },
      { label: "B", value: "Give one-word answers" },
      { label: "C", value: "Avoid examples" },
      { label: "D", value: "Change the topic" },
    ],
    answer: "Use the STAR method",
    explanation: "STAR = Situation, Task, Action, Result.",
    difficulty: "medium",
    category: "HR",
    tags: ["interview"],
  },

  // Networking
  {
    text: "What is the full form of HTTP?",
    type: "mcq",
    options: [
      { label: "A", value: "HyperText Transfer Protocol" },
      { label: "B", value: "High Transfer Text Protocol" },
      { label: "C", value: "HyperText Transmission Protocol" },
      { label: "D", value: "Hybrid Text Transfer Protocol" },
    ],
    answer: "HyperText Transfer Protocol",
    explanation:
      "HTTP stands for HyperText Transfer Protocol, used for web communication.",
    difficulty: "easy",
    category: "Networking",
    tags: ["protocols", "web"],
  },
  {
    text: "Which layer of OSI model handles routing?",
    type: "mcq",
    options: [
      { label: "A", value: "Data Link Layer" },
      { label: "B", value: "Transport Layer" },
      { label: "C", value: "Network Layer" },
      { label: "D", value: "Session Layer" },
    ],
    answer: "Network Layer",
    explanation:
      "The Network Layer (Layer 3) handles routing and forwarding of packets.",
    difficulty: "medium",
    category: "Networking",
    tags: ["OSI", "routing"],
  },
  {
    text: "What does HTTP stand for?",
    type: "mcq",
    options: [
      { label: "A", value: "Hyper Text Transfer Protocol" },
      { label: "B", value: "High Transfer Text Protocol" },
      { label: "C", value: "Hyper Transfer Test Protocol" },
      { label: "D", value: "Host Transfer Text Protocol" },
    ],
    answer: "Hyper Text Transfer Protocol",
    explanation:
      "HTTP is the protocol used for communication on the World Wide Web.",
    difficulty: "easy",
    category: "Networking",
    tags: ["http"],
  },
  {
    text: "Which device forwards data packets between networks?",
    type: "mcq",
    options: [
      { label: "A", value: "Switch" },
      { label: "B", value: "Hub" },
      { label: "C", value: "Router" },
      { label: "D", value: "Repeater" },
    ],
    answer: "Router",
    explanation: "Routers forward packets between different networks.",
    difficulty: "easy",
    category: "Networking",
    tags: ["router"],
  },
  {
    text: "What is the default port number of HTTP?",
    type: "mcq",
    options: [
      { label: "A", value: "21" },
      { label: "B", value: "25" },
      { label: "C", value: "80" },
      { label: "D", value: "443" },
    ],
    answer: "80",
    explanation: "HTTP uses port 80 by default.",
    difficulty: "easy",
    category: "Networking",
    tags: ["ports"],
  },
  {
    text: "What is the default port number of HTTPS?",
    type: "mcq",
    options: [
      { label: "A", value: "80" },
      { label: "B", value: "110" },
      { label: "C", value: "443" },
      { label: "D", value: "8080" },
    ],
    answer: "443",
    explanation: "HTTPS uses port 443 for secure communication.",
    difficulty: "easy",
    category: "Networking",
    tags: ["https"],
  },
  {
    text: "Which protocol is connection-oriented?",
    type: "mcq",
    options: [
      { label: "A", value: "UDP" },
      { label: "B", value: "TCP" },
      { label: "C", value: "IP" },
      { label: "D", value: "ARP" },
    ],
    answer: "TCP",
    explanation: "TCP establishes a connection before transmitting data.",
    difficulty: "medium",
    category: "Networking",
    tags: ["tcp"],
  },
  {
    text: "Which protocol is connectionless?",
    type: "mcq",
    options: [
      { label: "A", value: "TCP" },
      { label: "B", value: "FTP" },
      { label: "C", value: "UDP" },
      { label: "D", value: "HTTP" },
    ],
    answer: "UDP",
    explanation: "UDP sends data without establishing a connection.",
    difficulty: "medium",
    category: "Networking",
    tags: ["udp"],
  },
  {
    text: "What is the full form of DNS?",
    type: "mcq",
    options: [
      { label: "A", value: "Domain Name System" },
      { label: "B", value: "Dynamic Network Service" },
      { label: "C", value: "Data Name Server" },
      { label: "D", value: "Domain Network Service" },
    ],
    answer: "Domain Name System",
    explanation: "DNS translates domain names into IP addresses.",
    difficulty: "easy",
    category: "Networking",
    tags: ["dns"],
  },
  {
    text: "Which layer of OSI model is responsible for routing?",
    type: "mcq",
    options: [
      { label: "A", value: "Transport Layer" },
      { label: "B", value: "Network Layer" },
      { label: "C", value: "Session Layer" },
      { label: "D", value: "Data Link Layer" },
    ],
    answer: "Network Layer",
    explanation: "Routing is handled at the Network Layer.",
    difficulty: "medium",
    category: "Networking",
    tags: ["osi-model"],
  },
  {
    text: "How many layers are there in the OSI model?",
    type: "mcq",
    options: [
      { label: "A", value: "5" },
      { label: "B", value: "6" },
      { label: "C", value: "7" },
      { label: "D", value: "8" },
    ],
    answer: "7",
    explanation: "OSI model consists of 7 layers.",
    difficulty: "easy",
    category: "Networking",
    tags: ["osi-model"],
  },
  {
    text: "What is the primary purpose of an IP address?",
    type: "mcq",
    options: [
      { label: "A", value: "Identify a device on a network" },
      { label: "B", value: "Store files" },
      { label: "C", value: "Encrypt data" },
      { label: "D", value: "Increase speed" },
    ],
    answer: "Identify a device on a network",
    explanation: "IP addresses uniquely identify devices on a network.",
    difficulty: "easy",
    category: "Networking",
    tags: ["ip-address"],
  },

  // OOP
  {
    text: "Which OOP concept allows a class to inherit properties from multiple classes?",
    type: "mcq",
    options: [
      { label: "A", value: "Single Inheritance" },
      { label: "B", value: "Multiple Inheritance" },
      { label: "C", value: "Encapsulation" },
      { label: "D", value: "Polymorphism" },
    ],
    answer: "Multiple Inheritance",
    explanation:
      "Multiple inheritance allows a class to inherit from more than one parent class.",
    difficulty: "easy",
    category: "OOP",
    tags: ["inheritance", "OOP"],
  },
  {
    text: "What is method overriding?",
    type: "mcq",
    options: [
      {
        label: "A",
        value: "Defining two methods with the same name in one class",
      },
      {
        label: "B",
        value: "Redefining a parent class method in a child class",
      },
      { label: "C", value: "Hiding a method from other classes" },
      { label: "D", value: "Calling a method from another class" },
    ],
    answer: "Redefining a parent class method in a child class",
    explanation:
      "Method overriding allows a subclass to provide a specific implementation of a method in the parent class.",
    difficulty: "medium",
    category: "OOP",
    tags: ["polymorphism", "overriding"],
  },
  {
    text: "What is Encapsulation in OOP?",
    type: "mcq",
    options: [
      { label: "A", value: "Hiding data and methods inside a class" },
      { label: "B", value: "Creating multiple classes" },
      { label: "C", value: "Copying objects" },
      { label: "D", value: "Deleting objects" },
    ],
    answer: "Hiding data and methods inside a class",
    explanation:
      "Encapsulation bundles data and methods together and restricts direct access.",
    difficulty: "easy",
    category: "OOP",
    tags: ["encapsulation"],
  },
  {
    text: "What is Inheritance?",
    type: "mcq",
    options: [
      { label: "A", value: "Creating a new class from an existing class" },
      { label: "B", value: "Deleting a class" },
      { label: "C", value: "Hiding data" },
      { label: "D", value: "Creating objects" },
    ],
    answer: "Creating a new class from an existing class",
    explanation: "Inheritance allows code reusability.",
    difficulty: "easy",
    category: "OOP",
    tags: ["inheritance"],
  },
  {
    text: "Which OOP concept allows one interface with multiple implementations?",
    type: "mcq",
    options: [
      { label: "A", value: "Encapsulation" },
      { label: "B", value: "Polymorphism" },
      { label: "C", value: "Abstraction" },
      { label: "D", value: "Inheritance" },
    ],
    answer: "Polymorphism",
    explanation:
      "Polymorphism allows objects to behave differently based on context.",
    difficulty: "medium",
    category: "OOP",
    tags: ["polymorphism"],
  },
  {
    text: "What is Abstraction?",
    type: "mcq",
    options: [
      { label: "A", value: "Showing only essential details" },
      { label: "B", value: "Creating objects" },
      { label: "C", value: "Copying methods" },
      { label: "D", value: "Deleting classes" },
    ],
    answer: "Showing only essential details",
    explanation: "Abstraction hides implementation details from the user.",
    difficulty: "easy",
    category: "OOP",
    tags: ["abstraction"],
  },
  {
    text: "Which keyword is used to inherit a class in Java?",
    type: "mcq",
    options: [
      { label: "A", value: "inherits" },
      { label: "B", value: "extends" },
      { label: "C", value: "implements" },
      { label: "D", value: "super" },
    ],
    answer: "extends",
    explanation: "The 'extends' keyword is used for inheritance in Java.",
    difficulty: "easy",
    category: "OOP",
    tags: ["java"],
  },
  {
    text: "What is Method Overloading?",
    type: "mcq",
    options: [
      { label: "A", value: "Same method name with different parameters" },
      { label: "B", value: "Same method name in parent and child class" },
      { label: "C", value: "Deleting methods" },
      { label: "D", value: "Multiple classes" },
    ],
    answer: "Same method name with different parameters",
    explanation: "Method overloading is compile-time polymorphism.",
    difficulty: "medium",
    category: "OOP",
    tags: ["overloading"],
  },
  {
    text: "What is Method Overriding?",
    type: "mcq",
    options: [
      { label: "A", value: "Changing method parameters" },
      { label: "B", value: "Providing a new implementation in child class" },
      { label: "C", value: "Deleting a method" },
      { label: "D", value: "Creating constructors" },
    ],
    answer: "Providing a new implementation in child class",
    explanation: "Method overriding is runtime polymorphism.",
    difficulty: "medium",
    category: "OOP",
    tags: ["overriding"],
  },
  {
    text: "What is a Class?",
    type: "mcq",
    options: [
      { label: "A", value: "Blueprint for objects" },
      { label: "B", value: "A function" },
      { label: "C", value: "A variable" },
      { label: "D", value: "A package" },
    ],
    answer: "Blueprint for objects",
    explanation: "A class defines properties and behaviors of objects.",
    difficulty: "easy",
    category: "OOP",
    tags: ["class"],
  },
  {
    text: "What is an Object?",
    type: "mcq",
    options: [
      { label: "A", value: "Instance of a class" },
      { label: "B", value: "A package" },
      { label: "C", value: "A method" },
      { label: "D", value: "A variable" },
    ],
    answer: "Instance of a class",
    explanation: "Objects are created from classes.",
    difficulty: "easy",
    category: "OOP",
    tags: ["object"],
  },
  {
    text: "Which access modifier provides maximum restriction?",
    type: "mcq",
    options: [
      { label: "A", value: "public" },
      { label: "B", value: "protected" },
      { label: "C", value: "private" },
      { label: "D", value: "default" },
    ],
    answer: "private",
    explanation: "Private members can only be accessed within the same class.",
    difficulty: "easy",
    category: "OOP",
    tags: ["access-modifier"],
  },
  {
    text: "Can constructors be inherited?",
    type: "mcq",
    options: [
      { label: "A", value: "Yes" },
      { label: "B", value: "No" },
      { label: "C", value: "Only in Java" },
      { label: "D", value: "Only in C++" },
    ],
    answer: "No",
    explanation: "Constructors are not inherited by child classes.",
    difficulty: "medium",
    category: "OOP",
    tags: ["constructor"],
  },
  {
    text: "What is a Constructor?",
    type: "mcq",
    options: [
      { label: "A", value: "Special method used to initialize objects" },
      { label: "B", value: "Method used to delete objects" },
      { label: "C", value: "Class variable" },
      { label: "D", value: "Access modifier" },
    ],
    answer: "Special method used to initialize objects",
    explanation:
      "Constructors are automatically called during object creation.",
    difficulty: "easy",
    category: "OOP",
    tags: ["constructor"],
  },
  {
    text: "Which keyword refers to the current object in Java?",
    type: "mcq",
    options: [
      { label: "A", value: "self" },
      { label: "B", value: "current" },
      { label: "C", value: "this" },
      { label: "D", value: "super" },
    ],
    answer: "this",
    explanation: "'this' refers to the current object.",
    difficulty: "easy",
    category: "OOP",
    tags: ["java"],
  },
  {
    text: "Which keyword is used to call parent class constructor?",
    type: "mcq",
    options: [
      { label: "A", value: "this" },
      { label: "B", value: "extends" },
      { label: "C", value: "super" },
      { label: "D", value: "parent" },
    ],
    answer: "super",
    explanation:
      "'super' is used to access parent class members and constructors.",
    difficulty: "medium",
    category: "OOP",
    tags: ["inheritance"],
  },
  {
    text: "Which OOP principle promotes code reusability the most?",
    type: "mcq",
    options: [
      { label: "A", value: "Abstraction" },
      { label: "B", value: "Inheritance" },
      { label: "C", value: "Encapsulation" },
      { label: "D", value: "Polymorphism" },
    ],
    answer: "Inheritance",
    explanation:
      "Inheritance allows existing code to be reused in new classes.",
    difficulty: "easy",
    category: "OOP",
    tags: ["inheritance"],
  },
];

// ─── SEED FUNCTION ───────────────────────────────────────
const seedDB = async () => {
  try {
    await connectDB();

    // Clear existing data
    await User.deleteMany();
    await Question.deleteMany();
    await Quiz.deleteMany();
    console.log("🗑️  Cleared existing data");

    // Seed users
    const createdUsers = await User.create(users);
    const adminUser = createdUsers.find((u) => u.role === "admin");
    console.log(`👤 Created ${createdUsers.length} users`);

    // Seed questions
    const questionsWithCreator = questions.map((q) => ({
      ...q,
      createdBy: adminUser._id,
    }));
    const createdQuestions = await Question.create(questionsWithCreator);
    console.log(`❓ Created ${createdQuestions.length} questions`);

    // Helper to get question IDs by category
    const getQuestionsByCategory = (category, count) =>
      createdQuestions
        .filter((q) => q.category === category)
        .slice(0, count)
        .map((q) => q._id);

    // Seed quizzes
    const quizzes = [
      {
        title: "DSA Fundamentals",
        description: "Test your Data Structures and Algorithms knowledge",
        questions: getQuestionsByCategory("DSA", 25),
        duration: 50,
        category: "DSA",
        difficulty: "mixed",
        totalMarks: 50,
        createdBy: adminUser._id,
      },
      {
        title: "Operating Systems Basics",
        description: "Test your OS concepts and knowledge",
        questions: getQuestionsByCategory("OS", 13),
        duration: 25,
        category: "OS",
        difficulty: "mixed",
        totalMarks: 25,
        createdBy: adminUser._id,
      },
      {
        title: "DBMS Essentials",
        description: "Test your Database Management concepts",
        questions: getQuestionsByCategory("DBMS", 13),
        duration: 25,
        category: "DBMS",
        difficulty: "mixed",
        totalMarks: 25,
        createdBy: adminUser._id,
      },
      {
        title: "Aptitude & Reasoning",
        description: "Practice aptitude questions for placements",
        questions: getQuestionsByCategory("Aptitude", 33),
        duration: 70,
        category: "Aptitude",
        difficulty: "easy",
        totalMarks: 70,
        createdBy: adminUser._id,
      },
      {
        title: "HR Interview Preparation",
        description: "Common HR interview questions",
        questions: getQuestionsByCategory("HR", 18),
        duration: 20,
        category: "HR",
        difficulty: "easy",
        totalMarks: 18,
        createdBy: adminUser._id,
      },
      {
        title: "Computer Networks",
        description: "Networking fundamentals and protocols",
        questions: getQuestionsByCategory("Networking", 18),
        duration: 20,
        category: "Networking",
        difficulty: "mixed",
        totalMarks: 18,
        createdBy: adminUser._id,
      },
      {
        title: "Object Oriented Programming",
        description: "OOP concepts and principles",
        questions: getQuestionsByCategory("OOP", 18),
        duration: 20,
        category: "OOP",
        difficulty: "mixed",
        totalMarks: 18,
        createdBy: adminUser._id,
      },
      {
        title: "Placement Mega Mock Test",
        description: "Complete placement preparation test",
        questions: [
          ...getQuestionsByCategory("DSA", 10),
          ...getQuestionsByCategory("OS", 5),
          ...getQuestionsByCategory("DBMS", 5),
          ...getQuestionsByCategory("Aptitude", 10),
          ...getQuestionsByCategory("HR", 5),
          ...getQuestionsByCategory("Networking", 5),
          ...getQuestionsByCategory("OOP", 5),
        ],
        duration: 60,
        category: "Mixed",
        difficulty: "mixed",
        totalMarks: 45,
        createdBy: adminUser._id,
      },
    ];

    const createdQuizzes = await Quiz.create(quizzes);
    console.log(`📝 Created ${createdQuizzes.length} quizzes`);

    console.log("\n✅ Database seeded successfully!");
    console.log("─────────────────────────────────");
    console.log("Admin Login:");
    console.log("  Email   : admin@placeprep.com");
    console.log("  Password: admin123");
    console.log("─────────────────────────────────");
    console.log("Student Login:");
    console.log("  Email   : rahul@student.com");
    console.log("  Password: student123");
    console.log("─────────────────────────────────");

    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding error:", error.message);
    process.exit(1);
  }
};

seedDB();
